### ISSUE TITLE
Status of the project

### ISSUE THREAD

**Issue by ryszardtuora** [ipipan/combo#1]
As far as I know, this is a reimplementation of Combo in pytorch. What is the status of the project? I.e. is it in a representable state?

**Comment by mklimasz** [comment]
Feel free to check out https://gitlab.clarin-pl.eu/syntactic-tools/combo where the project is currently developed.
I would say its an extension than a reimplementation.
It recently had its v1.0.0 release :wink:

**Comment by mklimasz** [comment]
We have added a redirection link in the readme.
